### ISSUE TITLE
Front end

### ISSUE THREAD

**Issue by ChanuYu** [be9904/OSS_Collab#5]
This feature is needed for users to interface with this web app.

**Comment by ChanuYu** [comment]
맨 첫번째 칸(이름을 통하여 조회하는 칸)의 버튼 이름을 +add 말고 search로 수정하는 게 좋을 거 같아요.
또 search 버튼을 눌렀을 때 조회내용이 뜰 수 있는 칸을 따로 추가해주시면 좋겠습니다.

**Comment by wshf253** [comment]
일단 search 에다가 돋보기 아이콘으로 바꾸겠습니다.
조회 내용이 뜰 수 있는 칸은 그냥 빈 칸만 만들어 놓으면 되는 건가요?

**Comment by ChanuYu** [comment]
네 일단은 빈칸으로 만들어주세요 그리고 추가적으로 얘기드리고 싶은 게
1. id가 똑같은 게 있어요 id는 특정 element의 고유번호 같은 느낌으로 쓰는 게 좋으니 중복되게 하지 않는 게 좋아요. 작명하기 힘드실 수 있으니 일단 버튼 부분의 id는 제가 다 작명할게요. 어차피 제가 각 element에 접근해서 처리를 해야 하니까요. 
2. html 코드 구성방식을 좀 바꿨으면 해요 지금 보면 행 위주로 (이름란, 주식종목명란, 매수량란,... 이렇게) 묶여있더라고요 혹시라도 나중에 새로 정보입력하는 것(왼쪽)과 기존 정보를 수정하는 것(오른쪽)을 구분해서 각각 다른 기능을 추가하거나 서로 다르게 꾸밀 수도 있으니 새로추가하는 것끼리(왼쪽편끼리) 묶고 기존 정보를 수정하는 것끼리(오른쪽편끼리) 묶어주실 수 있을까요?
바쁘실 텐데 이 부분은 바로 안 해주셔도 될 거 같습니다.

**Comment by wshf253** [comment]
id 같은 경우에는 일단은 대충 이름만 붙인거라서 중복되는게 좀 있을 거에요

**Comment by ChanuYu** [comment]
아 아직 임시파일이라 그런거였군요 그럼 일단 위에서 말한 대로 버튼 부분은 제가 id 수정해서 사용할게요 왼쪽편은 new_add 기존의 정보 수정같은 경우는 exist_add이런식으로 작명하겠습니다.
